import { BODY_LONG, BODY_SHORT, type KudoCard } from "./kudos-shared";

/**
 * "All Kudos" feed mock data (F003), faithful to the MoMorph frame
 * "Sun* Kudos - Live board" (`MaZUn5xHXZ`). Split out of `kudos-cards.ts` to
 * keep that file under the 200-line cap; re-exported from there so existing
 * imports (`from "../../_lib/kudos-cards"`) keep working. Vertical list; some
 * cards carry a photo strip.
 */
export const ALL_KUDOS: readonly KudoCard[] = [
  {
    id: "all-1",
    senderName: "Huỳnh Dương Xuân Nhật",
    senderRole: "CEVC10",
    senderTier: "New Hero",
    receiverName: "Trần Minh Anh",
    receiverRole: "CEVC19",
    receiverTier: "Legend Hero",
    timeRange: "10:00 - 10/30/2025",
    title: "IDOL GIỚI TRẺ",
    body: BODY_LONG,
    hashtags: ["#Dedicated", "#Inspring"],
    likeCount: 1000,
    department: "CEVC",
    photos: ["photo-a", "photo-b", "photo-c", "photo-d", "photo-e", "photo-f"],
  },
  {
    id: "all-2",
    senderName: "Phạm Thu Hà",
    senderRole: "CEVC07",
    senderTier: "Rising Hero",
    receiverName: "Nguyễn Hoàng Linh",
    receiverRole: "CEVC12",
    receiverTier: "Legend Hero",
    timeRange: "09:15 - 10/28/2025",
    title: "NGƯỜI THẦM LẶNG",
    body: BODY_LONG,
    hashtags: ["#Teamwork", "#Support"],
    likeCount: 1000,
    department: "CEVC",
    photos: ["photo-a", "photo-b", "photo-c", "photo-d", "photo-e"],
  },
  {
    id: "all-3",
    senderName: "Lê Quốc Bảo",
    senderRole: "CEVC22",
    senderTier: "Legend Hero",
    receiverName: "Đỗ Khánh Chi",
    receiverRole: "CEVC05",
    receiverTier: "Rising Hero",
    timeRange: "14:40 - 10/25/2025",
    title: "CHỖ DỰA CỦA TEAM",
    body: BODY_SHORT,
    hashtags: ["#Leadership", "#Trust"],
    likeCount: 1000,
    department: "Product",
    photos: ["photo-a", "photo-b", "photo-c", "photo-d", "photo-e", "photo-f"],
  },
  {
    id: "all-4",
    senderName: "Vũ Ngọc Mai",
    senderRole: "CEVC14",
    senderTier: "Rising Hero",
    receiverName: "Hoàng Anh Tú",
    receiverRole: "CEVC30",
    receiverTier: "New Hero",
    timeRange: "16:20 - 10/22/2025",
    title: "SÁNG TẠO KHÔNG NGỪNG",
    body: BODY_LONG,
    hashtags: ["#Creative", "#Inspring"],
    likeCount: 1000,
    department: "Design",
    photos: ["photo-a", "photo-b", "photo-c", "photo-d", "photo-e"],
  },
  {
    id: "all-5",
    senderName: "Bùi Thanh Sơn",
    senderRole: "CEVC02",
    senderTier: "Legend Hero",
    receiverName: "Ngô Phương Thảo",
    receiverRole: "CEVC18",
    receiverTier: "Rising Hero",
    timeRange: "11:05 - 10/20/2025",
    title: "TẬN TÂM VỚI KHÁCH HÀNG",
    body: BODY_SHORT,
    hashtags: ["#Dedicated", "#Customer"],
    likeCount: 958,
    department: "Marketing",
  },
  {
    id: "all-6",
    senderName: "Đặng Hải Đăng",
    senderRole: "CEVC26",
    senderTier: "New Hero",
    receiverName: "Trịnh Bảo Ngọc",
    receiverRole: "CEVC09",
    receiverTier: "Rising Hero",
    timeRange: "08:30 - 10/18/2025",
    title: "NĂNG LƯỢNG TÍCH CỰC",
    body: BODY_LONG,
    hashtags: ["#Positive", "#Energy"],
    likeCount: 1104,
    department: "Operation",
  },
];
